version: '3.9'
services:
  blog-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=mustit
      - POSTGRES_PASSWORD=1033
      - POSTGRES_USER=postgres
    container_name: blog-db
    ports:
      - '5432:5432'
    volumes:
      - ./prisma:/prisma
    networks:
      - blog-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  blog-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-server
    ports:
      - '80:9900'
    environment:
      - POSTGRES_HOST=blog-db
    depends_on:
      blog-db:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
    networks:
      - blog-network
    command: /bin/sh -c "sleep 10 && npx prisma migrate deploy && npm run start:prod"
    restart: on-failure

networks:
  blog-network:
    driver: bridge
